### ISSUE TITLE
Changer le fond bleu par un gris clair

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#105]
ça reste mon avis, et t'es pas obligé d'être d'accord, mais ça me fait bizarre d'avoir deux boites bleues et une grise :

![image](https://user-images.githubusercontent.com/172286/108382429-1c4ccf00-7209-11eb-85dd-0d9d4af496fb.png)

**Comment by mitch10593** [comment]
en profiter pour rajouter un lien vers les profils des utilisateurs
