### ISSUE TITLE
Mapper les id des serveurs sur leurs libellés

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#136]
Ici par exemple ça serait mieux d'afficher "public" que "1":
![image](https://user-images.githubusercontent.com/172286/108590098-07378380-7362-11eb-8c7e-96ac01d26cbe.png)

**Comment by mitch10593** [comment]
c'est (déjà) prévu, avec l'intégration des stats slmod: on ajoute notre notion de serveur
