### ISSUE TITLE
Avoir un petit "fil" de nouvelles

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#137]
Est-ce que tu penses que ça serait possible, et souhaitable, d'avoir un bloc dynamique qui montrerait (si c'est faisable) l'acchalandage du TS, du Discord, et peut-être les derniers posts du forum ?

**Comment by mitch10593** [comment]
Pour ts, j'ai rajouté #169 

pour Discord: aucun intérêt (je pense). Tout le monde est tout le temps connecté à discord du moment qu'il est sur son PC, sans être vraiment là...

Les derniers posts du forum, ça doit être assez compliqué.

**Comment by mitch10593** [comment]
la partie pour TS a été réalisée dans #169 , pour discord: pas significatif car tout le monde est tout le temps connecté.

Je ferme l'issue.
