### ISSUE TITLE
salle d'ops ?

### ISSUE THREAD

**Issue by mitch10593** [VEAF/website#14]
La salle d'opérations est vide sur l'ancien site, cette rubrique doit-elle être reprise et adaptée ?

en l'état, je ne vois pas quoi placer dans cette section.

**Comment by davidp57** [comment]
à terme on pourrait avoir un calendrier des ops (genre, les jours de training et mission, les opex, les opint)

**Comment by mitch10593** [comment]
le module calendrier étant opérationnel, je ferme cette issue.
