### ISSUE TITLE
Afficher le nombre de membres et de cadets quelque part sur la front page ?

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#140]

**Comment by mitch10593** [comment]
Après discussion, on va essayer de rajouter cette information directement dans le roster des pilotes, à côté des libellés "tout le monde", "cadets", "membres"

**Comment by mitch10593** [comment]
Proposition sur le roster:
![image](https://user-images.githubusercontent.com/10455897/108622719-f73fa280-743a-11eb-966b-3186f859a337.png)


et en version responsive / petite résolution:
![image](https://user-images.githubusercontent.com/10455897/108622732-07f01880-743b-11eb-8393-0c91fe6ec394.png)
