### ISSUE TITLE
Voir l'avion sur lequel la personne vole en ce moment

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#164]
Est-ce qu'on a dans les infos l'avion sur lequel la personne vole (ou mieux : le nom du slot) ?

![image](https://user-images.githubusercontent.com/172286/108731939-5f6eb100-752d-11eb-839f-412898f13a90.png)

**Comment by mitch10593** [comment]
on a une partie de l'information dans la table players online:
![image](https://user-images.githubusercontent.com/10455897/108754949-e8461680-7546-11eb-9e62-ee0fe8b4c93e.png)

**Comment by mitch10593** [comment]
Et on retrouve ces infos dans la table pe_DataRaw (dans le champ payload)

![image](https://user-images.githubusercontent.com/10455897/108755248-4d9a0780-7547-11eb-8d26-9d64ead1b112.png)

**Comment by mitch10593** [comment]
On peut faire le lien, mais rien de simple (il faut aller chercher le json dans la bdd, et le parser).

On peut même en profiter pour extraire plus d'informations: météo, heure, qnh, saison, etc...

![image](https://user-images.githubusercontent.com/10455897/108755501-a1a4ec00-7547-11eb-9783-28a5ff819d28.png)

**Comment by davidp57** [comment]
Ça a l'air bien compliqué tout ça ; laisse tomber, c'était pour dire que ça serait cool si c'était facile.
