### ISSUE TITLE
Petite fautounette d'orthographe ^^

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#165]
![image](https://user-images.githubusercontent.com/172286/108732085-84632400-752d-11eb-8080-9abc252acce3.png)

**Comment by mitch10593** [comment]
techniquement, l'orthographe du mot **connecté** est correcte.

puisqu'on chipote, il me semble que c'est plutôt une faute de **grammaire**

**Comment by davidp57** [comment]
Pfff le mec on lui montre un truc à améliorer et il chipote ;)
