### ISSUE TITLE
calendrier - ajouter une gestion d'événements

### ISSUE THREAD

**Issue by mitch10593** [VEAF/website#172]
Le module du forum étant buggé (et très limité), je pense qu'il serait bien de prévoir un module calendrier sur le site pour:

- gérer des événements (mission, training, réunion, intervention serveur, autre)
- le sim concerné (DCS + map | BMS)
- les restrictions (membre, membre + cadet, tout le monde)
- gérer les participants (oui, non, peut-être)
- un date + heure + durée
- une description courte (title)
- une description longue (markdown, image ?!, liens, ...)

**Comment by mitch10593** [comment]
Si validé, prévoir:
- une vue calendrier
- un formulaire d'ajout / modification

**Comment by davidp57** [comment]
Compliqué, non ?

**Comment by mitch10593** [comment]
c'est un peu de boulot, mais comparé au module calendrier nodebb, ça nous permettrai de toutes façons de faire des trucs beaucoup plus sympa
comme un countdown du prochain événements sur la page d'accueil ;)

**Comment by Tjorkinthus** [comment]
un formulaire avec une icône par appareil et le compte loguer qui clic dessus valide sa présence... facile pour dire oui et directement avec le bon appareil...

**Comment by mitch10593** [comment]
fait dans #173 sauf pour la participation par module (je note l'idée dans un nouveau ticket #174).
