### ISSUE TITLE
Ajouter une pastille "notification" avec le nombre d'évènements...

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#191]
... pour la journée en cours dans le calendrier (et peut-être aussi dans une autre couleur ceux de la semaine ?)

**Comment by mitch10593** [comment]
Je pense qu'on peut même afficher tous les événements à venir "non lus".

Si l'utilisateur est connecté, on afficher le nombre d'événements "non lus".
Dès que l'utilisateur a consulté un événement (même si il n'a pas voté), on le comptabilise comme "lu".

On peut même rajouter une info (pastille ?) sur les événements non lus au niveau du calendrier.

**Comment by davidp57** [comment]
Ça ajoute des complexités dans l'interface je trouve.
Perso, je suis pour un simple compte des event de la journée ou de la semaine (ou les deux, en couleurs différentes) pour attirer l'attention de tous sur le fait qu'il y a un truc prévu ce soir.
