### ISSUE TITLE
Faire un menu "bookmarks" éditable par l'admin...

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#192]
...dans lequel on pourra regrouper des liens importants (forum, discord, certains tutos, documents importants, etc.) sous une arborescence.
Pas besoin d'un truc compliqué, on peut gérer tout ça en mode texte pour autant que le système sache le décoder.
Ex:
```
/Association/[Le forum](https://community.veaf.org/)
/Association/735/[Règlement du serveur public](https://tinyurl.com/veaf-server)
/[Armée de l'air](https://www.defense.gouv.fr/air/)

**Comment by mitch10593** [comment]
ça rejoint un peu le besoin évoqué dans #112

**Comment by davidp57** [comment]
carrément ; après j'aime bien ma proposition "simpliste" en texte simple.

**Comment by mitch10593** [comment]
fait dans #218
