### ISSUE TITLE
Modification des statistiques de fréquentation

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#222]
- Ajouter une page de statistique serveur sur la semaine (comme les stats horaires, pas la heatmap)
- Si possible permettre de sélectionner la plage avec des fléches gauche-droite (de jour en jour pour les stats journalières, de semaine en semaine pour les hebdo)
- Dans la heatmap, ajouter un filtre pour sélectionner quel type de pilote on veut prendre en compte (membres, cadets, invités)
- Toujours dans la heatmap, faire la moyenne sur 4 semaines

**Comment by mitch10593** [comment]
Heatmap: moyenne sur 4 semaines: fait.

**Comment by mitch10593** [comment]
Heatmap: filtrer par statut de l'utilistateur (membre, cadet, etc...): fait
