### ISSUE TITLE
MENU - Changement de position non effectif

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#225]
J'ai créé un élément de menu "735" et je lui ai donné une position qui le plaçait tout à la fin.
Du coup je l'ai édité et j'ai changé les positions du divider et de l'élément "nous rejoindre" mais ça ne change rien.
![image](https://user-images.githubusercontent.com/172286/111064480-7d885b00-84b4-11eb-8f4a-e722ae1c7300.png)
![image](https://user-images.githubusercontent.com/172286/111064483-80834b80-84b4-11eb-944e-bea894b825c1.png)

**Comment by mitch10593** [comment]
c'est pas normal, je regarde ;)

**Comment by mitch10593** [comment]
corrigé dans #226
