### ISSUE TITLE
Ajouter le jour de la semaine dans la date des évènements

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#238]
![image](https://user-images.githubusercontent.com/172286/112206097-d4f59c00-8c15-11eb-896e-2b3b20584515.png)

**Comment by mitch10593** [comment]
un truc comme ça ?

![image](https://user-images.githubusercontent.com/10455897/112521908-53307a80-8d9d-11eb-85e0-ec27027268d8.png)

**Comment by mitch10593** [comment]
![image](https://user-images.githubusercontent.com/10455897/112522012-73603980-8d9d-11eb-9240-f8d11817c67c.png)
![image](https://user-images.githubusercontent.com/10455897/112522179-9a1e7000-8d9d-11eb-94f1-c888715df9cb.png)

**Comment by davidp57** [comment]
Mitchissime !!!
