### ISSUE TITLE
module Mission Maker

### ISSUE THREAD

**Issue by akohen** [VEAF/website#240]
Afin de préparer les missions, les mission makers peuvent avoir besoin d'informations supplémentaires sur la répartition des modules parmi les membres et cadets. Par exemple, savoir combien de membres ont Persian Gulf et volent sur UH-1, F-5E ou F-16.

## Idées
* Afficher un tableau de tous les joueurs et l'état de chacun de leur modules
* Permettre aux mission makers de télécharger ces données sous format csv

**Comment by mitch10593** [comment]
en WIP, un screen qui correspond à l'exemple:
![image](https://user-images.githubusercontent.com/10455897/112378345-1904a180-8ce7-11eb-8c54-81f74cd99b63.png)

**Comment by davidp57** [comment]
Excellent !

**Comment by mitch10593** [comment]
et la version CSV
![image](https://user-images.githubusercontent.com/10455897/112516356-7b1cdf80-8d97-11eb-9024-7af3dd308e77.png)

**Comment by mitch10593** [comment]
fait dans #244  et #241
