### ISSUE TITLE
perun 0.12 - update schema

### ISSUE THREAD

**Issue by mitch10593** [VEAF/website#277]
> Salut @Mitch ; j'aimerais bien étudier la montée de version de Perun, si tu as le temps un de ces quatre matins.
> En pratique, il faut vérifier que la nouvelle version fonctionne sur le serveur de test (tout neuf), et mettre à jour la db ; y'a eu des changements de structure apparemment, ils disent :
> Some minor changes, which will broke your integrations - re-create DB with the attached SQL or manual update.
> 
> For manual update:
> 
> - change version in pe_Config
> - columns in pe_OnlineStatus were renamed
> - added column to pe_OnlinePlayers
> - message ids and content from pe_DataRaw were changed.
> https://github.com/szporwolik/perun/blob/master/04_MySQL/m1081_perun.sql
> https://github.com/szporwolik/perun/commit/9a5e86bae96f855de754b836aee98048a520253e#diff-d54c2718fee104568b561ba331f2cc3b71750f126320fb6bad957e930e90ba9c
> le souci, c'est surtout de trouver comment tester Perun 0.12.0 en ne cassant pas Perun 0.11.2
> Mais y'a pas d'urgence, pour le moment la version 0.11.2 fonctionne, sur le public (pas moyen de lancer sur le privé de manière certaine, ça plante parfois, je sais pas pourquoi)

**Comment by mitch10593** [comment]
Je vais préparer une migration de la base de données, et on câblera ça (le privé) sur le serveur "beta"

**Comment by mitch10593** [comment]
Côté paypload, je vais laisser le format "mediumtext":
https://electrictoolbox.com/maximum-length-mysql-text-field-types/

on peut déjà stocker un json de 16Mo, la taille max constatée actuellement est de 77 ko

**Comment by mitch10593** [comment]
c'est en test sur l'instance beta

**Comment by davidp57** [comment]
sur la bdd "website_beta" au lieu de "website"
