### ISSUE TITLE
profil - accentuer la séparation entre "activité" et "niveau"

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#49]
![image](https://user-images.githubusercontent.com/172286/107849896-80812480-6dfe-11eb-980f-e74fc3e36931.png)

**Comment by mitch10593** [comment]
fixé dans #54 
![image](https://user-images.githubusercontent.com/10455897/107853090-589cbb80-6e14-11eb-9bfa-1114f1e8b1aa.png)
