### ISSUE TITLE
roster - utiliser les mêmes icones que dans le profil

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#50]
Profil : 

![image](https://user-images.githubusercontent.com/172286/107849912-9b539900-6dfe-11eb-8fea-abf2508d8d96.png)

Roster :

![image](https://user-images.githubusercontent.com/172286/107849927-a73f5b00-6dfe-11eb-8547-dbc620232387.png)

**Comment by mitch10593** [comment]
fixé dans #54 
![image](https://user-images.githubusercontent.com/10455897/107853122-79651100-6e14-11eb-8ad3-d66553de1dc3.png)
