### ISSUE TITLE
utilisateurs - permettre la saisie de l'UCID de DCS dans la page d'édition

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#52]
Elle permet de faire le lien avec les pilotes récupérés dans Perun

**Comment by mitch10593** [comment]
fait, via la liste des joueurs DCS dans #57 

à voir si ça convient où si il faut ajouter cette notion sur la fiche utilisateur.

**Comment by mitch10593** [comment]
bon, à priori le fonctionnement est suffisant, je ferme ce ticket.
