### ISSUE TITLE
Permettre l'utilisation de styles dans les pages (markdown)

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#77]
C'est vraiment pas mal du tout d'avoir permis l'édition des pages, on a un vrai petit CMS !
Mais il faudrait quelques styles basiques pour permettre de faire des trucs propres (bullets, gras, etc.)
Est-ce que c'est possible de facilement permettre l'utilisation d'un moteur de style comme Markdown ?

![image](https://user-images.githubusercontent.com/172286/108034071-3fbf2080-7035-11eb-9878-98ea6a4cd3e3.png)

![image](https://user-images.githubusercontent.com/172286/108034089-48aff200-7035-11eb-9dd4-4b7359b054a2.png)

**Comment by mitch10593** [comment]
confirmé par @davidp57 , le markdown fonctionne bien en restitution.

il faudra prévoir un petit editeur JS pour avoir l'aperçu en live.

**Comment by davidp57** [comment]
Du coup pour ma part j'ai pas besoin de plus

**Comment by mitch10593** [comment]
ok, c'est cool.
