### ISSUE TITLE
permettre la gestion du recrutement

### ISSUE THREAD

**Issue by davidp57** [VEAF/website#94]
Il serait souhaitable d'avoir un écran dédié à la gestion du workflow de recrutement des cadets.
L'objectif serait de remplacer [la Google Sheet](https://docs.google.com/spreadsheets/d/1BpBAQ41dvfGBv2m63NX00QpmlMqakTgDUD7xzuGChtc/edit#gid=0) qui sert à ça actuellement. Je mets un screenshot pour les gens qui n'ont pas accès :
![image](https://user-images.githubusercontent.com/172286/108357840-4644c800-71ee-11eb-80a3-455b2a78779e.png)

Le workflow doit sans doute être revu pour l'occasion, mais actuellement il est le suivant :
- une personne arrive dans le système -> c'est un invité (qui peut être lié à un user du site, mais pas forcément) ; à ce stade on n'est pas obligé de l'entrer dans le site
- cette personne se présente et choisit le rôle de cadet -> elle devient un cadet, on doit noter ses informations (callsign, mail, identifiant forum et discord, date de début du recrutement)
- on lui présente l'association (date, personne)
- on fait des vols avec elle (ou d'autres activités impliquant des membres) ; chaque activité peut être enregistrée (date, personne) ou on peut compter les activités
- on prend une décision : soit on lui propose de nous rejoindre, soit on le vire du recrutement ; noter la décision, la date et la personne (si on le vire il redevient invité)
- il répond : soit il accepte, soit pas ; du coup il devient membre ou il redevient invité (noter la date)

**Comment by mitch10593** [comment]
Je propose (le site ayant un peu évolué en 1 mois):
- ajouter 2 champs à la fiche de l'utilisateur: pseudo discord + pseudo forum (+alerte sur le profil si l'utilisateur n'a pas complété ces informations, comme c'est le cas pour la partie "simulateur": l'utilisateur est autonome pour saisir ces informations
- dans la rubrique "mon profil", rappeler le statut (invité par défaut).

pour les invités:
- rajouter un bouton "devenir cadet" (qui explique en quoi ça consiste), on enregistre alors l'information (date/heure) dans une table événement.
cet événement a besoin d'un acquittement (que seul un "recruteur" ou un admin peut gérer)
- sur le profil d'un cadet, n'importe quel membre peut indiquer qu'il a présenté l'association (date/heure automatique ou saisie à la main ?)
- sur le profil d'un cadet, n'importe quel membre peut indiquer qu'il a effectué un vol (date/heure) et un commentaire (facultatif) et mentionner de façon normalisée une appréciation ? (genre: favorable, neutre, défavorable)
- sur le dashboard, on indique les cadets qui ont commencé leur programme, avec une alerte (délai arbitraire) et un récap des événements associés, du nombre d'événements favorables, etc...
- prise de décision: pour les membres "éligibles", un admin ou recruteur propose (et note l'événement proposition), en fonction de la décision (acquittement de cet événement), on transforme le cadet en membre ou en invité

en gros, on peut sur le modèle de données, tout gérer avec une table "événément" en conjonction avec le statut du membre:
- id
- date/heure ajout (technique)
- date/heure modification (technique) 
- date/heure corrigée / saisie par l'utilisateur (seule valeur pertinente pour l'utilisateur)
- type d'événement: postuler (passer de invité à cadet), présentation de l'association, vol effectué (plusieurs possibles), proposition de rejoindre, sortie du programme cadet, admission dans l'association

**Comment by mitch10593** [comment]
Première étape:

![image](https://user-images.githubusercontent.com/10455897/111539617-5e1c5700-876e-11eb-8cf0-15a41a470f78.png)

**Comment by davidp57** [comment]
Super Mitch, ça me parait parfait !

**Comment by mitch10593** [comment]
Symbologie dans la liste des pilotes (si on est ADMIN ou RECRUTEUR):

![image](https://user-images.githubusercontent.com/10455897/111821529-0e12d100-88e3-11eb-8ed5-f52632f5e136.png)

**Comment by mitch10593** [comment]
Un membre peut voir, sur le profil d'un cadet:
![image](https://user-images.githubusercontent.com/10455897/111826985-a449f580-88e9-11eb-9960-1c43a62bd912.png)

(c'est en wip)

- tout membre pourra ajouter un vol (prévoir une modale)
- les recruteurs pourront indiquer que la présentation a été effectuée
- les autres infos sont plus pour la partie technique

**Comment by mitch10593** [comment]
Un recruteur pour cocher la case "Présentation de l'association":

![image](https://user-images.githubusercontent.com/10455897/111833495-8a60e080-88f2-11eb-8546-bf78b8e53971.png)

**Comment by mitch10593** [comment]
Dans le roster des pilotes, les admin et recruteurs peuvent avoir l'information générale:
![image](https://user-images.githubusercontent.com/10455897/111868028-f5a0c600-8977-11eb-8731-7b02f68d02ff.png)

**Comment by mitch10593** [comment]
Ajout d'un vol avec le cadet:

![image](https://user-images.githubusercontent.com/10455897/111868119-6647e280-8978-11eb-82a5-547519b4dbef.png)

**Comment by mitch10593** [comment]
Et un petit historique des événements / vols:
![image](https://user-images.githubusercontent.com/10455897/111868362-d1de7f80-8979-11eb-8e89-55ca27d16a88.png)

**Comment by davidp57** [comment]
Mitchissime !

**Comment by mitch10593** [comment]
Retours (notes en vrac):

retour démo 

- Ti'rco
- Maddog

puis retour point Zip

Limiter "Mon parcours à la VEAF - 735th" aux personnes qui ont choisi DCS.

C'est un choix qui implique de participer régulièrement aux activités de la VEAF avec d'autres membres.

Après 5 activités, nous prendrons ensemble la décision de continuer ou pas.

Idéalement, cette période d'essai est d'un mois.

Lien Perun Lien Slmod: une seule coche (pas coché si un seul problème)

Je dois rencontrer un membre qui me présentera l'association, voici ici pour les contacts privilégiés.
(lien vers le forum). https://community.veaf.org/topic/584/guide-du-cadet

Intégrer La VEAF 

Majuscule: Je postule, Je reste.

lors du choix invité/cadet:
- indiquer la durée de la période d'essai
- indiquer que le choix n'est pas définitif

Présentation de l'association par un recruteur => non, par un membre
=> limiter le droit à tous les membres.

suivi du cadet:
- 
présentation sur le forum (checkbox possible ?) -> recruteur qui valide

ajouter pseudo

proposition de devenir membre (checkbox)
transformation de cadet 

=> invité (refusé)
=> membre

vols => activités
ajouter une activité

**Comment by mitch10593** [comment]
bon, je pense que notre fonctionnement est d'aplomb, créer une nouvelle issue si la solution en place n'est pas satisfaisante.
